print("1.", '2 < 5  --> ', 2 < 5)
print("2.", '2 <= 5  --> ', 2 <= 5)
print("3.", '3 > 3  --> ', 3 > 3)
print("4.", '3 >= 3  --> ', 3 >= 3)
print("5.", '3 == 3.0  --> ', 3 == 3.0)
print("6.", '3 == "3"  --> ', 3 == "3")
print("7.", '"3" == "3"  --> ', "3" == "3")
print("8.", '"3" == "3.0"  --> ', "3" == "3.0")
print("9.", '"syntax" == "syntax"  --> ', "syntax" == "syntax")
print("10.", '"syntax" == "semantiek"  --> ', "syntax" == "semantiek")
print("11.", '"syntax" == " syntax"  --> ', "syntax" == " syntax")
print("12.", '"Python" != "rotzooi"  --> ', "Python" != "rotzooi")
print("13.", '"Python" > "Perl"  --> ', "Python" > "Perl")
print("14.", '"banaan" < "mango" --> ', "banaan" < "mango")
print("15.", '"banaan" < "Mango"  --> ', "banaan" < "Mango")
print("15.", '"True" < "False"  --> ', "True" < "False")

